#!/bin/bash

while true; do
    echo "Hello world"
    while IFS= read -r line; do
        echo "$line"
        if [[ "$line" == "test" ]]; then
            break 2
        fi
    done | nc -l -p 98
done
