#!/usr/bin/env bash
# Running nginx as nginx and fixing port from 80 to 8080

# Stop Apache service if running
service apache2 stop

# Update Nginx configuration to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart Nginx service
sudo -u nginx service nginx restart
